"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type Recipe = { id: string; name: string; category: string; tags: string[]; temp: number; minutes: number; checkMinutes?: number; prep?: string; note?: string; custom?: boolean };

const base: Recipe[] = [
  { id: "karaage", name: "鶏の唐揚げ", category: "肉", tags: ["揚げ物"], temp: 190, minutes: 15, checkMinutes: 8, prep: "一口大に切り、下味をつけて15分置く。", note: "途中で一度バスケットを振るとカリッと。" },
  { id: "fries", name: "フライドポテト（冷凍）", category: "冷凍食品", tags: ["野菜"], temp: 195, minutes: 12, checkMinutes: 6, prep: "凍ったまま、表面の霜を軽く払う。", note: "重ならないように広げてください。" },
  { id: "salmon", name: "焼き鮭（厚切り）", category: "魚", tags: ["簡単"], temp: 230, minutes: 9, checkMinutes: 5, prep: "キッチンペーパーで水分を拭き、塩をふる。", note: "皮を下にして焼きます。" },
  { id: "vegetables", name: "ローストベジタブル", category: "野菜", tags: ["簡単"], temp: 195, minutes: 5, checkMinutes: 5, prep: "食べやすく切り、オイルを薄くまぶす。", note: "5分加熱 → シェイク → 160℃で5分" },
  { id: "sweet", name: "さつまいもスティック", category: "野菜", tags: [], temp: 190, minutes: 10, checkMinutes: 5, prep: "細長く切り、水にさらして水気を拭く。", note: "水にさらしてから水気を拭き取ります。" },
  { id: "nugget", name: "チキンナゲット", category: "冷凍食品", tags: ["肉"], temp: 200, minutes: 8, checkMinutes: 5, prep: "冷凍のまま、重ならないように並べる。", note: "お弁当にも便利な定番メニュー。" },
  { id: "mochi", name: "焼き餅", category: "簡単", tags: [], temp: 200, minutes: 8, note: "膨らみ始めたら様子を見て。" },
  { id: "sausage", name: "ウインナー", category: "肉", tags: ["簡単"], temp: 180, minutes: 5, note: "切れ目を入れると破裂しにくくなります。" },
  { id: "steak", name: "ステーキ（1～2cm）", category: "肉", tags: [], temp: 205, minutes: 5, note: "焼き上がり後、3分ほど休ませます。" },
  { id: "broccoli", name: "ブロッコリー", category: "野菜", tags: ["簡単"], temp: 180, minutes: 8, checkMinutes: 4, prep: "小房に分け、水気をしっかり拭いてオイルをまぶす。", note: "焼き色がついたら完成。茎も薄切りにして使えます。" },
  { id: "pumpkin", name: "かぼちゃ焼き", category: "野菜", tags: ["簡単"], temp: 190, minutes: 12, checkMinutes: 7, prep: "種とワタを取り、1cm幅に切る。", note: "皮を下にすると形が崩れにくくなります。" },
  { id: "asparagus", name: "アスパラガス", category: "野菜", tags: ["簡単"], temp: 190, minutes: 7, checkMinutes: 4, prep: "根元の硬い部分を切り、長ければ半分にする。", note: "塩とオイルだけでもおいしく仕上がります。" },
  { id: "mushroom", name: "きのこのマリネ焼き", category: "野菜", tags: [], temp: 180, minutes: 10, checkMinutes: 5, prep: "きのこを食べやすくほぐし、オイルと塩をまぶす。", note: "水分が飛んで香りが立つまで焼きます。" },
  { id: "eggplant", name: "なすの焼きびたし", category: "野菜", tags: [], temp: 200, minutes: 10, checkMinutes: 5, prep: "縦半分に切り、皮に浅く切り込みを入れる。", note: "焼き上がりにめんつゆへ浸します。" },
  { id: "corn", name: "とうもろこし", category: "野菜", tags: ["簡単"], temp: 190, minutes: 15, checkMinutes: 8, prep: "皮とひげを取り、表面の水分を拭く。", note: "途中で転がして全体を香ばしく焼きます。" },
  { id: "carrot", name: "にんじんグラッセ", category: "野菜", tags: [], temp: 180, minutes: 14, checkMinutes: 7, prep: "細長く切り、オイルと少量の塩をまぶす。", note: "柔らかくなったら、はちみつを絡めても。" },
  { id: "onion", name: "玉ねぎステーキ", category: "野菜", tags: ["簡単"], temp: 180, minutes: 15, checkMinutes: 8, prep: "厚めの輪切りにし、楊枝で形を固定する。", note: "表面がきつね色になるまで焼きます。" },
  { id: "chicken-steak", name: "チキンステーキ", category: "肉", tags: [], temp: 200, minutes: 15, checkMinutes: 8, prep: "厚い部分を開き、皮にフォークで穴をあける。", note: "皮を上にして焼くとパリッとします。" },
  { id: "chicken-wings", name: "手羽先", category: "肉", tags: ["揚げ物"], temp: 190, minutes: 17, checkMinutes: 10, prep: "水分を拭き、骨に沿って切り込みを入れる。", note: "途中で裏返し、全体に焼き色をつけます。" },
  { id: "pork-sauté", name: "ポークソテー", category: "肉", tags: [], temp: 190, minutes: 12, checkMinutes: 7, prep: "筋切りをして塩こしょうをふる。", note: "焼き上がり後に2分休ませます。" },
  { id: "meatballs", name: "ミートボール", category: "肉", tags: [], temp: 190, minutes: 12, checkMinutes: 6, prep: "同じ大きさに丸め、表面に薄くオイルを塗る。", note: "途中で転がしてまんべんなく焼きます。" },
  { id: "bacon", name: "ベーコン", category: "肉", tags: ["簡単"], temp: 180, minutes: 6, checkMinutes: 3, prep: "重ならないように並べる。", note: "脂が多いので短時間から様子を見ます。" },
  { id: "white-fish", name: "白身魚の香草焼き", category: "魚", tags: [], temp: 190, minutes: 12, checkMinutes: 7, prep: "水気を拭き、塩をふって薄力粉をまぶす。", note: "身が白くなり、箸でほぐれれば完成です。" },
  { id: "shrimp", name: "えびのガーリック焼き", category: "魚", tags: ["簡単"], temp: 190, minutes: 8, checkMinutes: 4, prep: "殻と背ワタを取り、水気を拭く。", note: "色が変わって丸まったら取り出します。" },
  { id: "saba", name: "塩さば", category: "魚", tags: ["簡単"], temp: 180, minutes: 10, checkMinutes: 6, prep: "表面の水分と余分な脂を拭く。", note: "皮側を上にして焼きます。" },
  { id: "scallop", name: "ほたてのバター焼き", category: "魚", tags: [], temp: 180, minutes: 8, checkMinutes: 4, prep: "水分を拭き、塩こしょうをふる。", note: "仕上げにバターをのせます。" },
  { id: "potato-wedges", name: "ポテト厚切り", category: "野菜", tags: [], temp: 190, minutes: 14, checkMinutes: 8, prep: "くし形に切り、水にさらして水気を拭く。", note: "途中でバスケットを振ります。" },
  { id: "zucchini", name: "ズッキーニ焼き", category: "野菜", tags: ["簡単"], temp: 190, minutes: 8, checkMinutes: 4, prep: "1cm厚さの輪切りにし、オイルをまぶす。", note: "チーズをのせてもおいしく仕上がります。" },
  { id: "tomato", name: "焼きトマト", category: "野菜", tags: ["簡単"], temp: 180, minutes: 8, checkMinutes: 5, prep: "へたを取り、半分に切る。", note: "チーズやパン粉をのせて焼けます。" },
  { id: "cabbage", name: "焼きキャベツ", category: "野菜", tags: ["簡単"], temp: 190, minutes: 10, checkMinutes: 5, prep: "芯を残して厚めのくし形に切る。", note: "表面に焼き色がつけば完成です。" },
  { id: "frozen-spring-roll", name: "冷凍春巻き", category: "冷凍食品", tags: ["揚げ物"], temp: 180, minutes: 15, checkMinutes: 9, prep: "凍ったまま表面にオイルを薄く塗る。", note: "皮がきつね色になるまで焼きます。" },
  { id: "frozen-croquette", name: "冷凍コロッケ", category: "冷凍食品", tags: ["揚げ物"], temp: 200, minutes: 14, checkMinutes: 8, prep: "凍ったまま、表面にオイルを吹きかける。", note: "衣が焦げそうなら温度を下げます。" },
  { id: "frozen-chicken", name: "冷凍チキンカツ", category: "冷凍食品", tags: ["肉", "揚げ物"], temp: 190, minutes: 15, checkMinutes: 9, prep: "凍ったまま間隔をあけて並べる。", note: "中心まで火が通ったか確認してください。" },
  { id: "frozen-pizza", name: "冷凍ピザ", category: "冷凍食品", tags: ["簡単"], temp: 180, minutes: 8, checkMinutes: 5, prep: "入る大きさに切り、凍ったまま置く。", note: "チーズが溶けて焼き色がつけば完成です。" },
  { id: "toast", name: "食パン・トースト", category: "簡単", tags: [], temp: 180, minutes: 5, checkMinutes: 3, prep: "バスケットに平らに置く。", note: "機種によって焦げやすいので早めに確認します。" },
  { id: "fried-tofu", name: "揚げ出し豆腐", category: "簡単", tags: [], temp: 200, minutes: 8, checkMinutes: 5, prep: "水切りして片栗粉をまぶす。", note: "表面がカリッとしたら取り出します。" },
];
const categories = ["すべて", "肉", "魚", "野菜", "冷凍食品", "揚げ物", "簡単"];
const icons: Record<string, string> = { 肉: "🍗", 魚: "🐟", 野菜: "🥦", 冷凍食品: "❄️", 揚げ物: "🍟", 簡単: "🌟" };
const formatTime = (minutes: number) => { const totalSeconds = Math.round(minutes * 60); return `${Math.floor(totalSeconds / 60)}分${String(totalSeconds % 60).padStart(2, "0")}秒`; };

export default function Home() {
  const [recipes, setRecipes] = useState(base); const [query, setQuery] = useState(""); const [category, setCategory] = useState("すべて");
  const [favorites, setFavorites] = useState<string[]>([]); const [history, setHistory] = useState<string[]>([]); const [tab, setTab] = useState("home");
  const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState({ name: "", category: "肉", temp: "180", minutes: "10", prep: "", note: "" });
  const [selected, setSelected] = useState<Recipe | null>(null);
  const [adjustments, setAdjustments] = useState<Record<string, { temp: number; minutes: number }>>({});
  const [photos, setPhotos] = useState<Record<string, string>>({}); const photoInput = useRef<HTMLInputElement>(null);
  const [plannerOpen, setPlannerOpen] = useState(false); const [planIds, setPlanIds] = useState<string[]>([]);
  const [layout, setLayout] = useState<"card" | "table">("card"); const [sort, setSort] = useState<"default" | "temp" | "minutes">("default"); const [descending, setDescending] = useState(false);
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem("airfryer-recipes") || "[]"); if (saved.length) setRecipes([...base, ...saved]); setFavorites(JSON.parse(localStorage.getItem("airfryer-favorites") || "[]")); setHistory(JSON.parse(localStorage.getItem("airfryer-history") || "[]")); setAdjustments(JSON.parse(localStorage.getItem("airfryer-adjustments") || "{}")); setPhotos(JSON.parse(localStorage.getItem("airfryer-photos") || "{}")); } catch { /* ignore */ } }, []);
  const visible = useMemo(() => { const result = recipes.filter((r) => { const search = `${r.name} ${r.category} ${r.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()); const cat = category === "すべて" || r.category === category || r.tags.includes(category); const mode = tab === "favorite" ? favorites.includes(r.id) : tab === "history" ? history.includes(r.id) : true; return search && cat && mode; }); if (sort === "default") return result; return [...result].sort((a, b) => { const diff = sort === "temp" ? a.temp - b.temp : a.minutes - b.minutes; return descending ? -diff : diff; }); }, [recipes, query, category, tab, favorites, history, sort, descending]);
  const favorite = (id: string) => { const next = favorites.includes(id) ? favorites.filter((x) => x !== id) : [id, ...favorites]; setFavorites(next); localStorage.setItem("airfryer-favorites", JSON.stringify(next)); };
  const viewed = (id: string) => { const next = [id, ...history.filter((x) => x !== id)].slice(0, 10); setHistory(next); localStorage.setItem("airfryer-history", JSON.stringify(next)); };
  const adjust = (recipe: Recipe, field: "temp" | "minutes", amount: number) => { const current = adjustments[recipe.id] || { temp: recipe.temp, minutes: recipe.minutes }; const nextValue = Math.max(field === "temp" ? 80 : 5 / 60, current[field] + amount); const next = { ...adjustments, [recipe.id]: { ...current, [field]: nextValue } }; setAdjustments(next); localStorage.setItem("airfryer-adjustments", JSON.stringify(next)); };
  const addPhoto = (file?: File) => { if (!file || !selected) return; const reader = new FileReader(); reader.onload = () => { const next = { ...photos, [selected.id]: String(reader.result) }; setPhotos(next); localStorage.setItem("airfryer-photos", JSON.stringify(next)); }; reader.readAsDataURL(file); };
  const save = (e: React.FormEvent) => { e.preventDefault(); if (!form.name.trim()) return; const item = { id: `custom-${Date.now()}`, name: form.name.trim(), category: form.category, tags: [], temp: +form.temp, minutes: +form.minutes, prep: form.prep, note: form.note, custom: true }; const next = [...recipes, item]; setRecipes(next); localStorage.setItem("airfryer-recipes", JSON.stringify(next.filter((x) => x.custom))); setFormOpen(false); setForm({ name: "", category: "肉", temp: "180", minutes: "10", prep: "", note: "" }); };
  const exportJson = () => { const blob = new Blob([JSON.stringify(recipes, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "airfryer-recipes.json"; a.click(); URL.revokeObjectURL(url); };
  const title = tab === "favorite" ? "お気に入り" : tab === "history" ? "最近見たレシピ" : "レシピ一覧";
  const planRecipes = recipes.filter((r) => planIds.includes(r.id)); const planMax = Math.max(...planRecipes.map((r) => r.minutes), 0);
  return <div className="app"><header><div className="logo"><span>🍳</span><div><b>Airfry Memo</b><small>ノンフライヤー調理メモ</small></div></div><nav><button className={tab === "home" ? "active" : ""} onClick={() => setTab("home")}>🏠<small>ホーム</small></button><button className={tab === "history" ? "active" : ""} onClick={() => setTab("history")}>🕘<small>履歴</small></button><button className={tab === "favorite" ? "active" : ""} onClick={() => setTab("favorite")}>💗<small>お気に入り</small></button><button onClick={() => setFormOpen(true)}>📝<small>追加</small></button></nav></header>
    <main><section className="hero"><div><p>毎日の「何度で何分？」を、もっと楽しく。</p><h1>今日の料理を<br /><i>らくらく</i>エアフライ。</h1><span>食材を選ぶだけで、ぴったりのレシピを選べます。</span></div><div className="hero-icon">🍗<b>190°</b><small>15 min</small><em>✦</em></div></section>
      <section className="tools"><div className="search"><span>🔍</span><input aria-label="メニューや食材で検索" placeholder="メニューや食材で検索..." value={query} onChange={(e) => setQuery(e.target.value)} />{query && <button onClick={() => setQuery("")}>×</button>}</div><div className="chips">{categories.map((c) => <button key={c} className={category === c ? "on" : ""} onClick={() => { setCategory(c); setTab("home"); }}>{icons[c] || "✨"} {c}</button>)}</div></section>
      <div className="heading"><div><small>QUICK COOKING GUIDE</small><h2>{title} <i>{visible.length}</i></h2></div><div className="list-tools"><button className="planner-button" onClick={() => setPlannerOpen(true)}>🧺 まとめて調理</button><div className="view-switch"><button className={layout === "card" ? "on" : ""} onClick={() => setLayout("card")}>▦ カード</button><button className={layout === "table" ? "on" : ""} onClick={() => setLayout("table")}>☷ 表</button></div><select value={sort} onChange={(e) => setSort(e.target.value as typeof sort)} aria-label="並び替え"><option value="default">おすすめ順</option><option value="temp">温度順</option><option value="minutes">時間順</option></select>{sort !== "default" && <button className="direction" onClick={() => setDescending(!descending)}>{descending ? "↓" : "↑"}</button>}<button className="json" onClick={exportJson}>⬇ JSON保存</button></div></div>
      {layout === "card" ? <div className="grid">{visible.map((r) => <article key={r.id} onClick={() => { viewed(r.id); setSelected(r); }}><div className="cardline"><span className="pill">{icons[r.category] || "✨"} {r.category}</span>{r.tags.map((t) => <span className="pill pale" key={t}>{icons[t] || "✨"} {t}</span>)}<button className={favorites.includes(r.id) ? "heart liked" : "heart"} onClick={(e) => { e.stopPropagation(); favorite(r.id); }}>{favorites.includes(r.id) ? "♥" : "♡"}</button></div><h3>{r.name}</h3><div className="numbers"><div>🌡️<small>温度</small><b>{r.temp}<i>℃</i></b></div><hr /><div>⏱️<small>時間</small><b>{r.minutes}<i>分</i></b></div></div><p className="memo">💡 {r.note || "様子を見ながら焼き加減を調整してください。"}</p><footer><span>詳細を見る</span><b>一緒に焼けるもの</b> <em>→</em></footer></article>)}</div> : <div className="table-wrap"><table><thead><tr><th>料理名</th><th>カテゴリ</th><th>温度</th><th>時間</th><th>途中確認</th><th>♡</th></tr></thead><tbody>{visible.map((r) => <tr key={r.id} onClick={() => { viewed(r.id); setSelected(r); }}><td><b>{icons[r.category] || "✨"} {r.name}</b></td><td><span className="pill pale">{r.category}</span></td><td>🌡️ <strong>{r.temp}℃</strong></td><td>⏱️ <strong>{r.minutes}分</strong></td><td>{r.checkMinutes || Math.max(5, Math.round(r.minutes / 2))}分ごろ</td><td><button className={favorites.includes(r.id) ? "heart liked" : "heart"} onClick={(e) => { e.stopPropagation(); favorite(r.id); }}>{favorites.includes(r.id) ? "♥" : "♡"}</button></td></tr>)}</tbody></table></div>}
      {!visible.length && <div className="empty">🍽️<h3>レシピが見つかりません</h3><p>検索条件を変えるか、新しいレシピを追加してみましょう。</p></div>}<aside>🌿 <div><b>設定値は目安です</b><span>食材の量・厚み・機種によって変わります。様子を見ながら調整してください。</span></div></aside>
    </main><div className="bottom"><b>Airfry Memo</b><span>おいしい毎日を、もっとかんたんに。</span></div>
    {selected && <div className="backdrop" onClick={() => setSelected(null)}><section className="detail" onClick={(e) => e.stopPropagation()}><button className="close" onClick={() => setSelected(null)}>×</button>{photos[selected.id] ? <img className="recipe-photo" src={photos[selected.id]} alt={`${selected.name}の写真`} /> : <div className="detail-emoji">{icons[selected.category] || "✨"}</div>}<input ref={photoInput} className="photo-input" type="file" accept="image/*" capture="environment" onChange={(e) => addPhoto(e.target.files?.[0])} /><button className="photo-button" onClick={() => photoInput.current?.click()}>📷 {photos[selected.id] ? "写真を変更" : "写真を追加"}</button><div className="cardline"><span className="pill">{icons[selected.category] || "✨"} {selected.category}</span>{selected.tags.map((t) => <span className="pill pale" key={t}>{icons[t] || "✨"} {t}</span>)}</div><h2>{selected.name}</h2><p className="detail-lead">基準値から、好みに合わせて調整できます。</p><div className="adjust-numbers"><div><span>🌡️<small>温度</small></span><button onClick={() => adjust(selected, "temp", -5)} aria-label="温度を下げる">−</button><b>{adjustments[selected.id]?.temp ?? selected.temp}<i>℃</i></b><button onClick={() => adjust(selected, "temp", 5)} aria-label="温度を上げる">＋</button><em>基準 {selected.temp}℃</em></div><div><span>⏱️<small>時間（5秒刻み）</small></span><button onClick={() => adjust(selected, "minutes", -5 / 60)} aria-label="時間を5秒減らす">−</button><b>{formatTime(adjustments[selected.id]?.minutes ?? selected.minutes)}</b><button onClick={() => adjust(selected, "minutes", 5 / 60)} aria-label="時間を5秒増やす">＋</button><em>基準 {formatTime(selected.minutes)}</em></div></div><div className="check-time">👀 <b>途中で様子を見る目安</b><span>{selected.checkMinutes || Math.max(5, Math.round(selected.minutes / 2))}分ごろに一度、焼き色と火の通りを確認</span></div><div className="tip prep-tip"><strong>🔪 下処理</strong><p>{selected.prep || "食材の水分を拭き、食べやすい大きさに整える。"}</p></div><div className="tip"><strong>💡 調理のコツ</strong><p>{selected.note || "焼き色を確認しながら、お好みの焼き加減に調整してください。"}</p></div><div className="pair"><span>🍽️ 一緒に焼けるもの</span><b>{selected.category === "肉" ? "ポテト・野菜" : selected.category === "野菜" ? "チキン・ソーセージ" : "なし"}</b></div><button className="save" onClick={() => favorite(selected.id)}>{favorites.includes(selected.id) ? "♥ お気に入り済み" : "♡ お気に入りに追加"}</button></section></div>}
    {plannerOpen && <div className="backdrop" onClick={() => setPlannerOpen(false)}><section className="planner" onClick={(e) => e.stopPropagation()}><button className="close" onClick={() => setPlannerOpen(false)}>×</button><small>COOKING PLANNER</small><h2>まとめて調理 🧺</h2><p className="planner-lead">一緒に調理するレシピを選んでください。</p><div className="plan-picker">{recipes.map((r) => <label key={r.id} className={planIds.includes(r.id) ? "picked" : ""}><input type="checkbox" checked={planIds.includes(r.id)} onChange={() => setPlanIds(planIds.includes(r.id) ? planIds.filter((id) => id !== r.id) : [...planIds, r.id])} /><span>{icons[r.category] || "✨"}</span><b>{r.name}</b><em>{r.temp}℃ / {r.minutes}分</em></label>)}</div>{planRecipes.length > 0 && <><div className="timeline-head"><b>調理タイムライン</b><span>{planRecipes.length}品・最長 {planMax}分</span></div><div className="timeline">{[...planRecipes].sort((a, b) => b.minutes - a.minutes).map((r) => <div className="timeline-row" key={r.id}><strong>{r.name}</strong><span>開始：{planMax - r.minutes}分後</span><b>取り出し：{planMax}分後</b></div>)}</div><p className="planner-note">※同じ温度で調理する想定です。途中で焼き色を確認し、食材ごとに先に取り出してください。</p></>}</section></div>}
    {formOpen && <div className="backdrop" onClick={() => setFormOpen(false)}><form onSubmit={save} onClick={(e) => e.stopPropagation()}><button type="button" className="close" onClick={() => setFormOpen(false)}>×</button><small>MY RECIPE</small><h2>レシピを追加 🥣</h2><label>料理名<input required placeholder="例：鮭のホイル焼き" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><div className="row"><label>カテゴリ<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{categories.slice(1, 6).map((c) => <option key={c}>{c}</option>)}</select></label><label>温度<input type="number" value={form.temp} onChange={(e) => setForm({ ...form, temp: e.target.value })} /></label><label>分<input type="number" value={form.minutes} onChange={(e) => setForm({ ...form, minutes: e.target.value })} /></label></div><label>🔪 下処理<textarea placeholder="例：一口大に切り、水気を拭く" value={form.prep} onChange={(e) => setForm({ ...form, prep: e.target.value })} /></label><label>💡 ひとことメモ<textarea value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} /></label><button className="save">保存する ✨</button></form></div>}
  </div>;
}
